### ISSUE TITLE
Failed to get destination ERROR

### ISSUE THREAD

**Issue by Ind791** [SAP/cloud-sdk-java#507] opened 2024-07-24 15:13 UTC
## Issue Description
Hello,
I'am trying to reach a destination by using the DestinationAccessor api of the java cloud sdk library but I'am facing the following error

2024-07-17T12:52:54.485+0000 [APP/PROC/WEB/0] STDOUT 2024-07-17T12:52:54.485Z  INFO 7 --- [nio-8080-exec-8] c.e.s.ServiceGetCredential               : ServiceGetCredential::getSolCredentialProtect - Name Destination Credential Store PLTS005_CRED_STORE
2024-07-17T12:52:54.487+0000 [APP/PROC/WEB/0] STDOUT 2024-07-17T12:52:54.487Z  INFO 7 --- [nio-8080-exec-8] c.s.c.s.c.c.DestinationAccessor          : Creating a new DestinationLoaderChain with EnvVarDestinationLoader as the primary DestinationLoader implementation.
2024-07-17T12:52:54.503+0000 [APP/PROC/WEB/0] STDOUT 2024-07-17T12:52:54.503Z  INFO 7 --- [nio-8080-exec-8] c.s.c.s.c.c.DestinationAccessor          : Using an instance of ScpCfDestinationLoader as the secondary DestinationLoader implementation.
2024-07-17T12:52:54.602+0000 [APP/PROC/WEB/0] STDOUT 2024-07-17T12:52:54.602Z ERROR 7 --- [nio-8080-exec-8] c.e.s.ServiceGetCredential               : Failed to get destination with name 'PLTS005_CRED_STORE'.

in attachment you can find the code snippet and the definition of the destination.
[Failed to get destination ERROR.docx](https://github.com/user-attachments/files/16364099/Failed.to.get.destination.ERROR.docx)

**Comment by KavithaSiva** [comment] 2024-07-25 08:09
Hi @Ind791,

Can you also attach the stack trace from your application to see what is the cause of the issue?
Please also attach your maven dependency tree.

Regards,
Kavitha

**Comment by Naucana** [comment] 2024-07-25 10:10
Hi @KavithaSiva,

Here in attachment are the requested files.

Regards,
Nauzet

[Maven dependency tree.txt](https://github.com/user-attachments/files/16374183/Maven.dependency.tree.txt)
[Stack Trace.txt](https://github.com/user-attachments/files/16374187/Stack.Trace.txt)

**Comment by KavithaSiva** [comment] 2024-07-25 12:36
Hi @Naucana,

There seems to be a mix-up of XSUAA v2 and v3 artifacts in your dependency tree(artifacts in groupId `com.sap.cloud.security`).
Please manage your XSUAA dependency versions by using `com.sap.cloud.security:java-bom`(v3.3.1) in your dependency management section. This should hopefully solve the issue.

Also, please note that we no longer provide support for version 4  of the SAP Cloud SDK, [please update to version 5](https://sap.github.io/cloud-sdk/docs/java/guides/5.0-upgrade-steps).

Regards,
Kavitha

**Comment by Naucana** [comment] 2024-07-30 13:25
Hi @KavithaSiva,

This solution works for us.
Can you proceed to close this issue?

Thank you so much for the support.

Regars,
Nauzet

**Comment by KavithaSiva** [comment] 2024-07-30 14:07
Hi @Naucana,
Good to know that the issue is resolved now.

**Closed by KavithaSiva** 2024-07-30 14:07 UTC
